# Versão Final para o Portainer
services:
  frontend:
    # Diz ao Portainer para usar a imagem que construímos manualmente
    image: cardio-learn-pro-frontend:latest
    container_name: cardio-learn-pro-frontend
    ports:
      - "8080:80"

  backend:
    # Diz ao Portainer para usar a imagem que construímos manualmente
    image: cardio-learn-pro-backend:latest
    container_name: cardio-learn-pro-backend
    ports:
      - "3001:3001"
    # Garante que a pasta de materiais seja persistente
    volumes:
      - ./functions/materiais:/app/materiais
